Update licenses, junit version
javaee/activation pull request #1
Opened 2018-02-21 14:57 UTC by vinayvishal

2018-02-21 17:03 UTC, bshannon requested changes
The Junit version update is fine.
The spec license should not be removed.
The copyright text was purposely left off the mailcap and mime.types files to avoid the runtime overhead of reading and discarding all those lines.  Please don't change those files.

2018-02-22 05:30 UTC, vinayvishal commented
1. Reverted the deletion of speclicense.html.

1. Reverted the changes done in mime.types and mailcap files.

1. Deleted all but *.txt files from doc/spec as per the review comments.

1. LICENSE.txt will be updated in corresponding EF repository.

2018-02-24 01:15 UTC, bshannon requested changes
Comments sent by email.

2018-02-27 18:41 UTC, bshannon approved these changes

2018-03-19 05:15 UTC, merged